Repository TravelScheduleService/BonVoyage, pull requests merged in 2024-03, with the labels that each got.

#12 #7 icon작성하기
  public/assets/icon/addBoxIcon.svg
  public/assets/icon/calendarIcon.svg
  public/assets/icon/closeIcon.svg
  public/assets/icon/codeitSmileIcon.svg
  public/assets/icon/crownIcon.svg
  public/assets/icon/dropDownArrowIcon.svg
  public/assets/icon/emailIcon.svg
  public/assets/icon/eyeOffIcon.svg
  public/assets/icon/eyeOnIcon.svg
  public/assets/icon/facebookIcon.svg
  public/assets/icon/forwardArrowIcon.svg
  public/assets/icon/instagramIcon.svg
  public/assets/icon/kebabMenuIcon.svg
  public/assets/icon/searchIcon.svg
  public/assets/icon/settingsIcon.svg
  public/assets/icon/unsubscribeIcon.svg
Labels: ✨기능구현, 상

#19 [Set] 프리티어 설정
  .github/ISSUE_TEMPLATE/✨feature.md
  .github/ISSUE_TEMPLATE/🐛fix.md
  .prettierrc.json
  package-lock.json
  package.json
  pull_request_template.md
  src/api/api.ts
  src/api/axios.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
Labels: 상

#13 [Refactor] 코드 리뷰 반영 및 mixin 수정
  package-lock.json
  package.json
  public/assets/icon/dotIcon.svg
  public/assets/icon/plusIcon.svg
  src/containers/atoms/ChipNumber/ChipNumber.module.scss
  src/containers/atoms/ChipNumber/ChipNumber.tsx
  src/containers/atoms/ChipTag/ChipTag.module.scss
  src/containers/atoms/ChipTag/ChipTag.tsx
  src/containers/molecules/ChipAdd/ChipAdd.module.scss
  src/containers/molecules/ChipAdd/ChipAdd.tsx
  src/containers/molecules/ChipProgress/ChipProgress.module.scss
  src/containers/molecules/ChipProgress/ChipProgress.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: ✨기능구현, 중

#34 [Chore] 할 일 페이지 폴더 구조 변경
  src/components/atoms/input/commentInput/CreateDoItYourselfComment.tsx
  src/components/atoms/input/createDoItYourselfCommonInput/CreateDoItYourselfInput.tsx
  src/components/atoms/input/createDoItYourselfCommonInput/createDoItYourselfInput.module.scss
  src/components/atoms/input/createDoItYourselfCommonTextarea/CreateDoItYourselfTextarea.tsx
  src/components/atoms/input/createDoItYourselfCommonTextarea/createDoItYourselfTextarea.module.scss
  src/components/atoms/input/dateInput/CreateDoItYourselfDate.tsx
  src/components/atoms/input/dateInput/createDoItYourselfDate.module.scss
  src/components/atoms/input/descriptionInput/CreateDoItYourselfDescription.tsx
  src/components/atoms/input/titleInput/CreateDoItYourselfTitle.tsx
  src/components/molecules/input/CreateDoItYourselfTag.tsx
Labels: 하

#37 [Feat] 헤더 작성 1차
  package-lock.json
  package.json
  src/components/atoms/logoWithTitle/LogoWithTitle.tsx
  src/components/atoms/logoWithTitle/logoWithTitle.module.scss
  src/components/molecules/header/headerAuth/HeaderAuth.tsx
  src/components/molecules/header/headerAuth/headerAuth.module.scss
Labels: ✨기능구현, 중

#38 [Feat] 헤더 컴포넌트 작성
  src/components/atoms/sideBar/sideBar.module.scss
  src/components/molecules/header/headerAuth/headerAuth.module.scss
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/header/headerMyDashboard/headerMyDashboard.module.scss
  src/pages/test.tsx
Labels: ✨기능구현, 중

#45 [Fix] 헤더 및 사이드바 css정형화 및 대시보드 페이지 작성
  src/components/atoms/colorDot/BigColorDot.tsx
  src/components/atoms/profileIcon/ProfileIcon.tsx
  src/components/atoms/profileIcon/profileIcon.module.scss
  src/components/atoms/sideBar/sideBar.module.scss
  src/components/molecules/editDashboardName/EditDashboardTitle.tsx
  src/components/molecules/editDashboardName/editDashboardTitle.module.scss
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/header/headerMyDashboard/headerMyDashboard.module.scss
  src/pages/editdashboard.tsx
  src/styles/editDashboard.module.scss
Labels: 🐛버그, ✨기능구현, 상

#41 [Feat] 새 대시보드 생성, 대시보드 목록 추가
  src/@types/type.ts
  src/components/atoms/baseModal/BaseModal.tsx
  src/components/atoms/baseModal/baseModal.module.scss
  src/components/atoms/buttons/myDashboardBtn/index.tsx
  src/components/atoms/colorDot/ColorDot.tsx
  src/components/atoms/imageInput/ImageInput.tsx
  src/components/atoms/imageInput/imageInput.module.scss
  src/components/atoms/logoWithTitle/LogoWithTitle.tsx
  src/components/atoms/sideBar/SideBar.tsx
  src/components/atoms/sideBar/sideBar.module.scss
  src/components/atoms/sideBarMenu/SideBarMenu.tsx
  src/components/icon/CheckIcon.tsx
  src/components/icon/ForwardArrowIcon.tsx
  src/components/icon/LeftArrowIcon.tsx
  src/components/molecules/ChipAdd/ChipAdd.tsx
  src/components/molecules/chipTag/ChipTag.module.scss
  src/components/molecules/chipTag/ChipTag.tsx
  src/components/molecules/createDashboardModal/CreateDashboardModal.tsx
  src/components/molecules/createDashboardModal/createDashboardModal.module.scss
  src/components/molecules/imageInput/ImageInput.tsx
  src/components/molecules/input/CreateDoItYourselfTag.tsx
  src/components/molecules/myDashboardList/MyDashboardList.tsx
  src/components/molecules/myDashboardList/myDashboardList.module.scss
  src/components/molecules/statusDropDown/StatusDropDown.tsx
  src/pages/_app.tsx
  src/pages/mydashboard.tsx
  src/styles/globals.css
  src/styles/myDashboard.module.scss
Labels: ✨기능구현, 상

#44 [Fix] signUp 페이지 이동 오류 수정
  src/components/atoms/input/common/CommonInput.tsx
  src/components/atoms/input/emailInput/EmailInput.tsx
  src/components/atoms/input/nicknameInput/NicknameInput.tsx
  src/components/atoms/input/passwordConfirmInput/passwordConfirmInput.tsx
  src/components/atoms/input/passwordInput/PasswordInput.tsx
  src/pages/login/index.tsx
  src/pages/signUp/index.tsx
Labels: 🐛버그

#48 [Feat]계정관리 페이지
  src/@types/type.ts
  src/api/accountApi/accountApi.ts
  src/api/axios.ts
  src/components/atoms/buttons/button/Button.module.scss
  src/components/atoms/input/common/CommonInput.tsx
  src/components/atoms/logoWithTitle/LogoWithTitle.tsx
  src/components/atoms/sideBarMenu/SideBarMenu.tsx
  src/components/molecules/account/account.module.scss
  src/components/molecules/account/index.tsx
  src/components/molecules/account/passwordChangeForm/index.tsx
  src/components/molecules/account/passwordChangeForm/passwordChangeForm.module.scss
  src/components/molecules/account/profileForm/index.tsx
  src/components/molecules/account/profileForm/profileForm.module.scss
  src/components/molecules/imageInput/ImageInput.tsx
  src/components/molecules/layout/index.tsx
  src/components/molecules/layout/layout.module.scss
  src/components/molecules/myHeader/MyHeader.tsx
  src/components/molecules/statusDropDown/statusDropDown.module.scss
  src/pages/myPage/index.tsx
  src/pages/myPage/mypage.module.scss
  src/styles/globals.css
  구상도.excalidraw
Labels: ✨기능구현, 중

#50 [Feat] edit페이지 구성원 컴포넌트 작성
  src/components/atoms/buttons/pagenationBtn/PagenationBtn.module.scss
  src/components/molecules/editDashboardName/editDashboardTitle.module.scss
  src/components/molecules/inviteList/InviteList.tsx
  src/components/molecules/inviteList/inviteList.module.scss
  src/components/molecules/members/Members.tsx
  src/components/molecules/members/members.module.scss
  src/pages/editdashboard.tsx
  src/styles/editDashboard.module.scss
Labels: ✨기능구현, 중

#51 [Feat] 계정관리 페이지 데이터 연결
  src/@types/type.ts
  src/api/accountApi/accountApi.ts
  src/api/axios.ts
  src/components/atoms/sideBar/sideBar.module.scss
  src/components/atoms/sideBarMenu/sideBarMenu.module.scss
  src/components/molecules/account/account.module.scss
  src/components/molecules/account/index.tsx
  src/components/molecules/account/passwordChangeForm/index.tsx
  src/components/molecules/account/passwordChangeForm/passwordChangeForm.module.scss
  src/components/molecules/account/profileForm/index.tsx
  src/components/molecules/account/profileForm/profileForm.module.scss
  src/components/molecules/imageInput/ImageInput.tsx
  src/components/molecules/layout/index.tsx
  src/components/molecules/layout/layout.module.scss
  src/components/molecules/myHeader/MyHeader.tsx
  src/pages/404/index.tsx
  src/pages/index.tsx
  src/pages/myPage/index.tsx
  src/pages/myPage/mypage.module.scss
Labels: ✨기능구현, 중

#55 [Feat] 대시보드 클릭시 페이지 이동 추가
  src/components/atoms/sideBar/sideBar.module.scss
  src/components/molecules/myDashboardList/MyDashboardList.tsx
  src/components/molecules/myHeader/MyHeader.tsx
Labels: ✨기능구현, 하

#58 [Feat] 로그인/회원가입 API 구현
  .editorconfig
  src/@types/index.d.ts
  src/@types/type.ts
  src/api/auth/authApi.ts
  src/api/axios.ts
  src/components/atoms/input/emailInput/EmailInput.tsx
  src/hooks/useSessionStorage.ts
  src/pages/login/index.tsx
  src/pages/login/login.module.scss
  src/pages/signUp/index.tsx
  src/pages/signUp/signUp.module.scss
  src/styles/_mixins.scss
Labels: ✨기능구현, 중

#57 [Feat] 계정관리 페이지
  public/assets/icon/errorPage.png
  src/@types/type.ts
  src/api/accountApi/accountApi.ts
  src/components/atoms/sideBar/sideBar.module.scss
  src/components/molecules/account/passwordChangeForm/index.tsx
  src/components/molecules/account/profileForm/index.tsx
  src/components/molecules/myHeader/MyHeader.tsx
  src/pages/404/errprPage.module.scss
  src/pages/404/index.tsx
Labels: ✨기능구현, 중

#59 [Feat] 대시보드 api연동
  src/api/axios.ts
  src/components/atoms/input/columnNameInput/ColumnNameInput.tsx
  src/components/atoms/input/createDoItYourselfCommonInput/CreateDoItYourselfInput.tsx
  src/components/atoms/sideBar/SideBar.tsx
  src/components/atoms/sideBar/sideBar.module.scss
  src/components/molecules/card/Card.tsx
  src/components/molecules/cardSection/CardSection.tsx
  src/components/molecules/cardSection/cardSection.module.scss
  src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
  src/pages/dashboard/[id]/index.tsx
  src/styles/dashboard.module.scss
Labels: ✨기능구현, 상

#64 [Bug] userChangeAccount타입에러 수정, 404페이지 로고 추가
  src/api/accountApi/accountApi.ts
  src/components/molecules/layout/index.tsx
  src/pages/404/index.tsx
Labels: 🐛버그, 하

#60 [Feat] 초대된 대시보드 목록 무한 스크롤 적용
  package-lock.json
  package.json
  src/api/dashboardListApi/dashboardListApi.ts
  src/components/atoms/imageInput/ImageInput.tsx
  src/components/molecules/invitedDashboardList/InvitedDashboardList.tsx
  src/components/molecules/myDashboardList/MyDashboardList.tsx
  src/components/molecules/myHeader/MyHeader.tsx
  src/components/molecules/myHeader/myHeader.module.scss
  src/pages/mydashboard/index.tsx
Labels: ✨기능구현, 중

#65 [Bug] SNS 로그인 버튼 추가 및 accessToken 저장 형식 변경
  public/assets/icon/googleIcon.svg
  public/assets/icon/kakaotalkIcon.svg
  src/@types/type.ts
  src/components/atoms/buttons/button/Button.module.scss
  src/components/atoms/buttons/button/index.tsx
  src/pages/login/index.tsx
  src/pages/login/login.module.scss
Labels: 🐛버그, 중

#67 [Feat] 컬럼 관련 기능 구현
  src/components/molecules/cardSection/CardSection.tsx
  src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
  src/components/molecules/modals/deleteColumnModal/DeleteColumnModal.tsx
  src/components/molecules/modals/editColumnModal/EditColumnModal.tsx
  src/components/molecules/myDashboardList/MyDashboardList.tsx
Labels: ✨기능구현, 상

#69 [Feat] 대시보드 수정 컴포넌트 추가 및 렌더링 오류 수정
  src/components/atoms/logoWithTitle/LogoWithTitle.tsx
  src/components/atoms/logoWithTitle/logoWithTitle.module.scss
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/header/headerMyDashboard/headerMyDashboard.module.scss
  src/components/molecules/inviteList/InviteList.tsx
  src/components/molecules/inviteList/inviteList.module.scss
  src/components/molecules/members/members.module.scss
  src/pages/editdashboard.tsx
  src/styles/editDashboard.module.scss
Labels: 🐛버그, ✨기능구현

#71 📝 docs: PR템플릿 수정
  pull_request_template.md
Labels: 📄문서, 하

#74 [Feat] 할 일 생성 모달 구현
  src/@types/type.ts
  src/api/auth/authApi.ts
  src/api/axios.ts
  src/api/cards/cardApi.ts
  src/api/columns/columnApi.ts
  src/api/members/memberApi.ts
  src/components/atoms/buttons/button/index.tsx
  src/components/atoms/input/columnNameInput/ColumnNameInput.tsx
  src/components/atoms/input/createDoItYourselfCommonInput/CreateDoItYourselfInput.tsx
  src/components/atoms/input/createDoItYourselfCommonInput/createDoItYourselfInput.module.scss
  src/components/atoms/input/dateInput/CreateDoItYourselfDate.tsx
  src/components/atoms/input/dateInput/createDoItYourselfDate.module.scss
  src/components/atoms/input/descriptionInput/CreateDoItYourselfDescription.tsx
  src/components/atoms/input/titleInput/CreateDoItYourselfTitle.tsx
  src/components/molecules/card/Card.tsx
  src/components/molecules/cardSection/CardSection.tsx
  src/components/molecules/imageInput/ImageInput.tsx
  src/components/molecules/imageInput/imageInput.module.scss
  src/components/molecules/input/CreateDoItYourselfTag.tsx
  src/components/molecules/input/createDoItYourselfTag.module.scss
  src/components/molecules/managerDropDown/ManagerDropDown.tsx
  src/components/molecules/managerDropDown/managerDropDown.module.scss
  src/components/molecules/modals/createCardModal/CreateCardModal.tsx
  src/components/molecules/modals/createCardModal/createCardModal.module.scss
  src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
  src/components/molecules/modals/editColumnModal/EditColumnModal.tsx
  src/pages/login/index.tsx
Labels: ✨기능구현, 상

#72 [Refactor] MyHeader, HeaderMyDashboard 통합
  src/components/atoms/sideBar/sideBar.module.scss
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/header/headerMyDashboard/headerMyDashboard.module.scss
  src/contexts/DashboardListContext.tsx
  src/pages/_app.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/mydashboard/index.tsx
  src/pages/mydashboard/myDashboard.module.scss
Labels: 하

#73 [Feat] 랜딩페이지 만들기
  public/assets/icon/whiteEmailIcon.svg
  public/assets/icon/whiteFacebook.svg
  public/assets/icon/whiteInstragram.svg
  src/@types/type.ts
  src/components/molecules/account/passwordChangeForm/index.tsx
  src/components/molecules/account/profileForm/index.tsx
  src/components/molecules/account/profileForm/profileForm.module.scss
  src/components/molecules/header/headerAuth/HeaderAuth.tsx
  src/components/molecules/header/headerAuth/headerAuth.module.scss
  src/components/molecules/landing/landingFooter/index.tsx
  src/components/molecules/landing/landingFooter/landingFooter.module.scss
  src/components/molecules/landing/landingHeader/index.tsx
  src/components/molecules/landing/landingHeader/landingHeader.module.scss
  src/components/molecules/landing/landingMain/index.tsx
  src/components/molecules/landing/landingMain/landingMain.module.scss
  src/components/molecules/layout/index.tsx
  src/components/molecules/myHeader/MyHeader.tsx
  src/components/molecules/myHeader/myHeader.module.scss
  src/components/molecules/profileDropdown/index.tsx
  src/components/molecules/profileDropdown/profileDropdown.module.scss
  src/pages/index.tsx
  src/pages/myPage/index.tsx
  src/styles/Home.module.scss
  구상도.excalidraw
Labels: ✨기능구현, 중

#75 [Chore] EditorConfig 플러그인 설치 추천 추가
  .vscode/extensions.json
  src/@types/type.ts
Labels: 하

#76 [Style] 할 일 생성 모달 내 달력 css 수정
  src/components/atoms/input/createDoItYourselfCommonInput/CreateDoItYourselfInput.tsx
  src/components/atoms/input/dateInput/CreateDoItYourselfDate.tsx
  src/components/atoms/input/dateInput/createDoItYourselfDate.module.scss
  src/components/molecules/card/Card.tsx
  src/pages/_app.tsx
  src/styles/datePicker.css
Labels: 중

#79 [Feat] 페이지 캐러셀 제작
  public/assets/image/back1.jpg
  public/assets/image/back2.jpg
  public/assets/image/back3.jpg
  public/assets/image/back4.jpg
  public/assets/image/back5.jpg
  public/assets/image/dashboardimg.png
  public/assets/image/inviteimg.png
  public/assets/image/listimg.png
  public/assets/image/memberImg.png
  src/components/molecules/account/account.module.scss
  src/components/molecules/account/index.tsx
  src/components/molecules/account/profileForm/index.tsx
  src/components/molecules/landing/landingCarousel/index.tsx
  src/components/molecules/landing/landingCarousel/landingCarousel.module.scss
  src/components/molecules/landing/landingMain/index.tsx
  src/components/molecules/landing/landingMain/landingMain.module.scss
  src/components/molecules/layout/index.tsx
  src/components/molecules/modals/editCardModal/EditCardModal.tsx
  src/components/molecules/myHeader/myHeader.module.scss
  src/components/molecules/profileImageInput/ProfileImageInput.module.scss
  src/components/molecules/profileImageInput/index.tsx
  src/pages/index.tsx
  src/pages/myPage/index.tsx
  src/pages/test.tsx
Labels: ✨기능구현, 하

#81 [Feat] 사이드 바 대시보드 목록 추가
  src/@types/type.ts
  src/components/atoms/buttons/pagenationBtn/index.tsx
  src/components/atoms/profileIcon/ProfileIcon.tsx
  src/components/atoms/profileIcon/profileIcon.module.scss
  src/components/atoms/sideBar/SideBar.tsx
  src/components/atoms/sideBar/sideBar.module.scss
  src/components/atoms/sideBarMenu/SideBarMenu.tsx
  src/components/atoms/sideBarMenu/sideBarMenu.module.scss
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/header/headerMyDashboard/headerMyDashboard.module.scss
  src/components/molecules/modals/cardDetailModal/cardDetailModal.module.scss
  src/components/molecules/statusDropDown/statusDropDown.module.scss
  src/pages/mydashboard/index.tsx
Labels: ✨기능구현, 중

#83 [Refactor] 대시보드 목록 호버시 내용 보이기 추가
  src/components/atoms/sideBar/SideBar.tsx
  src/components/atoms/sideBar/sideBar.module.scss
  src/components/atoms/sideBarMenu/sideBarMenu.module.scss
  src/components/molecules/statusDropDown/StatusDropDown.tsx
Labels: ✨기능구현

#84 [Feat] 랜딩페이지 이미지 수정
  public/assets/image/mainboard.png
  src/components/molecules/account/profileForm/index.tsx
  src/components/molecules/header/headerAuth/headerAuth.module.scss
  src/components/molecules/landing/landingMain/index.tsx
  src/components/molecules/landing/landingMain/landingMain.module.scss
Labels: 🐛버그, 하

#86 [Feat] 댓글 관련 기능 구현
  src/components/atoms/input/commentInput/CreateDoItYourselfComment.tsx
  src/components/atoms/input/createDoItYourselfCommonTextarea/CreateDoItYourselfTextarea.tsx
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
  src/components/molecules/modals/cardDetailModal/cardDetailModal.module.scss
Labels: ✨기능구현

#87 [docs] README.md 초안
  README.md
Labels: 📄문서, 하

#89 ♻️ refactor: 헤더 컴포넌트 통합
  src/components/atoms/profileIcon/ProfileIcon.tsx
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/header/headerMyDashboard/headerMyDashboard.module.scss
  src/components/molecules/layout/index.tsx
  src/pages/dashboard/[id]/edit.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/mydashboard/index.tsx
Labels: 🐛버그, 상

#90 [Fix] 유저 정보조회 데이터 위치 수정
  package-lock.json
  package.json
  src/components/molecules/account/profileForm/index.tsx
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/landing/landingCarousel/index.tsx
  src/components/molecules/layout/index.tsx
  src/components/molecules/myHeader/MyHeader.tsx
  src/components/molecules/myHeader/myHeader.module.scss
  src/components/molecules/profileDropdown/index.tsx
  src/components/molecules/profileDropdown/profileDropdown.module.scss
  src/pages/_app.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/myPage/index.tsx
Labels: 🐛버그, 하

#91 [Fix] 로그인 후 유저 데이터 불러오지 못하는 부분 수정
  src/components/atoms/input/common/CommonInput.tsx
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/pages/login/index.tsx
Labels: 🐛버그, 중

#93 [Fit] 프로필 드랍다운 디자인, 버튼 에러, 캐러셀 에러 수정
  src/components/atoms/buttons/eventDashboardBtn/EventDashboardBtn.module.scss
  src/components/atoms/buttons/eventDashboardBtn/index.tsx
  src/components/atoms/defaultProfileImage/defaultProfileImage.module.scss
  src/components/atoms/defaultProfileImage/index.tsx
  src/components/atoms/logoWithTitle/LogoWithTitle.tsx
  src/components/atoms/profileIcon/profileIcon.module.scss
  src/components/molecules/account/profileForm/index.tsx
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/header/headerMyDashboard/headerMyDashboard.module.scss
  src/components/molecules/landing/landingCarousel/index.tsx
  src/components/molecules/profileDropdown/index.tsx
  src/components/molecules/profileDropdown/profileDropdown.module.scss
  src/components/molecules/profileImageInput/index.tsx
Labels: 🐛버그, 하

#97 [Fix] 할 일 수정 모달 수정
  .eslintrc.json
  package-lock.json
  package.json
  src/@types/type.ts
  src/api/members/memberApi.ts
  src/components/atoms/chipNumber/ChipNumber.tsx
  src/components/atoms/chipTag/ChipTagWithoutX.tsx
  src/components/atoms/column/ColumnComponent.tsx
  src/components/atoms/input/commentInput/CreateDoItYourselfComment.tsx
  src/components/atoms/input/dateInput/CreateDoItYourselfDate.tsx
  src/components/atoms/input/titleInput/CreateDoItYourselfTitle.tsx
  src/components/atoms/kebapMenu/KebapMenu.tsx
  src/components/molecules/card/Card.tsx
  src/components/molecules/cardDetailKebap/CardDetailKebap.tsx
  src/components/molecules/cardSection/CardSection.tsx
  src/components/molecules/imageInput/ImageInput.tsx
  src/components/molecules/input/CreateDoItYourselfTag.tsx
  src/components/molecules/managerDropDown/ManagerDropDown.tsx
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
  src/components/molecules/modals/createCardModal/CreateCardModal.tsx
  src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
  src/components/molecules/modals/deleteCardModal/DeleteCardModal.tsx
  src/components/molecules/modals/editCardModal/EditCardModal.tsx
  src/components/molecules/profileDropdown/index.tsx
  src/components/molecules/profileImageInput/index.tsx
  src/hooks/contexts.ts
  src/hooks/createStateContext.ts
  src/pages/_app.tsx
  src/pages/dashboard/[id]/index.tsx
Labels: 🐛버그

#94 [Feat] 대시보드 수정 페이지 일부 기능 추가
  src/api/members/memberApi.ts
  src/components/atoms/colorDot/BigColorDot.tsx
  src/components/atoms/input/inviteInput/inviteInput.tsx
  src/components/atoms/profileIcon/ProfileIcon.tsx
  src/components/molecules/createDashboardModal/CreateDashboardModal.tsx
  src/components/molecules/editDashboardName/EditDashboardTitle.tsx
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/inviteList/InviteList.tsx
  src/components/molecules/members/Members.tsx
  src/components/molecules/modals/inviteMemberModal/InviteMemberModal.tsx
  src/components/molecules/modals/inviteMemberModal/inviteMemberModal.module.scss
  src/pages/dashboard/[id]/edit.tsx
  src/pages/dashboard/[id]/index.tsx
  src/styles/colorList.tsx
Labels: ✨기능구현, 중

#98 [Fix] 일부 컴포넌트 반응형css, 기증 수정
  src/components/atoms/column/column.module.scss
  src/components/atoms/input/createDoItYourselfCommonTextarea/createDoItYourselfTextarea.module.scss
  src/components/molecules/card/card.module.scss
  src/components/molecules/cardSection/CardSection.tsx
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
  src/components/molecules/modals/cardDetailModal/cardDetailModal.module.scss
  src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
  src/pages/dashboard/[id]/index.tsx
Labels: 🐛버그

#99 [Feat] SNS 로그인 기능 구현
  package-lock.json
  package.json
  src/@types/type.ts
  src/api/auth/authApi.ts
  src/components/atoms/buttons/button/index.tsx
  src/components/atoms/defaultProfileImage/index.tsx
  src/components/atoms/input/createDoItYourselfCommonTextarea/CreateDoItYourselfTextarea.tsx
  src/components/molecules/account/profileForm/index.tsx
  src/components/molecules/header/headerAuth/HeaderAuth.tsx
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
  src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
  src/components/molecules/profileDropdown/index.tsx
  src/hooks/useAuth.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/dashboard/[id]/index.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/login/login.module.scss
  src/styles/_mixins.scss
  src/styles/globals.css
Labels: ✨기능구현, 상

#101 [Fix] 할 일 생성/삭제 컴포넌트, 상세보기 컴포넌트, Card 컴포넌트 수정
  src/@types/type.ts
  src/api/api.ts
  src/api/auth/authApi.ts
  src/api/dashboardInfoApi/dashboardInfoApi.ts
  src/api/index.ts
  src/api/members/memberApi.ts
  src/components/atoms/profileIcon/ProfileIcon.tsx
  src/components/molecules/account/profileForm/index.tsx
  src/components/molecules/card/Card.tsx
  src/components/molecules/card/card.module.scss
  src/components/molecules/editDashboardName/EditDashboardTitle.tsx
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/imageInput/ImageInput.tsx
  src/components/molecules/inviteList/InviteList.tsx
  src/components/molecules/managerDropDown/ManagerDropDown.tsx
  src/components/molecules/members/Members.tsx
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
  src/components/molecules/modals/createCardModal/CreateCardModal.tsx
  src/components/molecules/modals/createCardModal/createCardModal.module.scss
  src/components/molecules/modals/deleteCardModal/DeleteCardModal.tsx
  src/components/molecules/modals/deleteCardModal/deleteCardModal.module.scss
  src/components/molecules/modals/editCardModal/editCardModal.module.scss
  src/components/molecules/modals/inviteMemberModal/InviteMemberModal.tsx
  src/pages/dashboard/[id]/edit.tsx
  src/pages/dashboard/[id]/index.tsx
  src/styles/globals.css
Labels: 🐛버그

#106 [Fix] 할일 태그 및 프로필 이미지 css 수정
  src/components/molecules/card/Card.tsx
  src/components/molecules/card/card.module.scss
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
  src/components/molecules/modals/cardDetailModal/cardDetailModal.module.scss
Labels: 🐛버그

#108 [Design] 랜딩페이지 CSS 수정
  public/assets/image/back1.jpg
  public/assets/image/back2.jpg
  public/assets/image/back3.jpg
  public/assets/image/back4.jpg
  public/assets/image/back5.jpg
  src/components/molecules/landing/landingCarousel/index.tsx
  src/components/molecules/landing/landingHeader/index.tsx
  src/components/molecules/landing/landingHeader/landingHeader.module.scss
  src/components/molecules/landing/landingMain/index.tsx
  src/components/molecules/landing/landingMain/landingMain.module.scss
  src/styles/Home.module.scss
Labels: 하

#110 [Fix] map 사용된 곳에 key prop 설정 등
  src/components/atoms/kebapMenu/KebapMenu.tsx
  src/components/molecules/card/Card.tsx
  src/components/molecules/editDashboardName/EditDashboardTitle.tsx
  src/components/molecules/inviteList/InviteList.tsx
  src/components/molecules/managerDropDown/ManagerDropDown.tsx
  src/components/molecules/members/Members.tsx
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
  src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
  src/components/molecules/modals/deleteCardModal/DeleteCardModal.tsx
  src/components/molecules/modals/inviteMemberModal/InviteMemberModal.tsx
  src/components/molecules/statusDropDown/StatusDropDown.tsx
  src/pages/api/auth/[...nextauth].js
  src/pages/dashboard/[id]/index.tsx
  src/pages/signUp/index.tsx
Labels: 🐛버그

#113 [Fix]배포오류수정
  src/components/atoms/kebapMenu/KebapMenu.tsx
  src/components/molecules/card/Card.tsx
  src/components/molecules/managerDropDown/ManagerDropDown.tsx
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
  src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
  src/components/molecules/modals/deleteCardModal/DeleteCardModal.tsx
  src/components/molecules/modals/deleteColumnModal/DeleteColumnModal.tsx
  src/components/molecules/modals/editColumnModal/EditColumnModal.tsx
  src/components/molecules/modals/inviteMemberModal/InviteMemberModal.tsx
  src/components/molecules/statusDropDown/StatusDropDown.tsx
  src/pages/api/auth/[...nextauth].js
  src/pages/dashboard/[id]/index.tsx
  src/pages/signUp/index.tsx
Labels: 🐛버그

#114 [hotfix] 랜딩페이지대문자 수정
  src/components/molecules/account/passwordChangeForm/index.tsx
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/profileDropdown/index.tsx
  src/pages/index.tsx
Labels: 🐛버그, 하

#115 fix: 배포 오류 수정
  src/components/molecules/card/Card.tsx
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
Labels: 🐛버그

#116 [Hotfix] useEffect, useRouter 클라이언트 훅을 HeaderAuth로 이동
  src/components/molecules/header/headerAuth/HeaderAuth.tsx
  src/pages/index.tsx
Labels: 🐛버그

#117 [Fix]: key prop 및 기타 오류 수정
  src/components/molecules/card/Card.tsx
  src/components/molecules/header/headerMyDashboard/HeaderMyDashboard.tsx
  src/components/molecules/invitedDashboardList/InvitedDashboardList.tsx
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
Labels: 🐛버그

#118 [Hotfix] Context를 사용하여 columns에 대한 Props Drilling 해소
  src/@types/type.ts
  src/api/members/memberApi.ts
  src/components/atoms/column/ColumnComponent.tsx
  src/components/atoms/kebapMenu/KebapMenu.tsx
  src/components/molecules/card/Card.tsx
  src/components/molecules/cardDetailKebap/CardDetailKebap.tsx
  src/components/molecules/cardSection/CardSection.tsx
  src/components/molecules/inviteList/InviteList.tsx
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
  src/components/molecules/modals/editCardModal/EditCardModal.tsx
  src/components/molecules/statusDropDown/StatusDropDown.tsx
  src/hooks/contexts.ts
  src/hooks/useAuth.ts
  src/pages/dashboard/[id]/index.tsx
  src/pages/mydashboard/index.tsx
Labels: 🐛버그

#120 [Fix] CommentProps 타입 오류 해결
  next.config.mjs
  src/components/atoms/input/commentInput/CreateDoItYourselfComment.tsx
  src/components/atoms/input/createDoItYourselfCommonTextarea/CreateDoItYourselfTextarea.tsx
Labels: 🐛버그

#121 [Fix] 이미지 alt 속성 추가
  src/components/atoms/sideBar/SideBar.tsx
  src/components/atoms/sideBarMenu/SideBarMenu.tsx
  src/components/molecules/card/Card.tsx
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
Labels: 🐛버그

#122 [Hotfix] 빌드 오류 해결 및 css 수정
  src/api/cards/cardApi.ts
  src/components/atoms/column/ColumnComponent.tsx
  src/components/atoms/input/createDoItYourselfCommonTextarea/CreateDoItYourselfTextarea.tsx
  src/components/molecules/card/Card.tsx
  src/components/molecules/card/card.module.scss
  src/components/molecules/cardSection/CardSection.tsx
  src/components/molecules/imageInput/ImageInput.tsx
  src/components/molecules/modals/cardDetailModal/CardDetailModal.tsx
  src/components/molecules/modals/createCardModal/CreateCardModal.tsx
  src/components/molecules/modals/editCardModal/EditCardModal.tsx
  src/components/molecules/statusDropDown/StatusDropDown.tsx
  src/hooks/contexts.ts
  src/pages/dashboard/[id]/index.tsx
Labels: 🐛버그

#123 [Fix] 랜딩페이지 이미지 변경 및 Card 컴포넌트 Tag join 되어있던 코드 제거 후 수정, 회원가입 안되는 버그 수정
  next.config.mjs
  public/assets/image/maindashboard.png
  src/components/molecules/card/Card.tsx
  src/components/molecules/card/card.module.scss
  src/components/molecules/landing/landingMain/index.tsx
  src/components/molecules/landing/landingMain/landingMain.module.scss
  src/pages/signUp/index.tsx
Labels: 🐛버그

#127 [Fix] 관리 페이지에서 초대 안 되는 오류 수정
  src/components/molecules/managerDropDown/ManagerDropDown.tsx
  src/components/molecules/modals/createColumnModal/CreateColumnModal.tsx
  src/components/molecules/modals/inviteMemberModal/InviteMemberModal.tsx
  src/hooks/contexts.ts
  src/pages/dashboard/[id]/edit.tsx
Labels: 🐛버그
